- block:
    - name: Install EPEL
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present

    - name: Install base packages and Ansible
      yum:
        name:
          - sshpass
          - vim
          - ansible
        state: latest
        enablerepo: epel-testing

  when: install_ansible

- name: Install packages on control
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - git

- name: Create ssh dir
  file:
    state: directory
    path: /home/{{ username }}/.ssh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: o-rwx

- name: Clone lightbulb
  git:
    accept_hostkey: yes
    clone: yes
    dest: /home/{{ username }}/lightbulb
    repo: https://github.com/ansible/lightbulb.git
    force: yes

- name: Update Perms for Git Clone
  file:
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    path: /home/{{ username }}/lightbulb

- name: Remove things that students don't need
  file:
    state: absent
    path: /home/{{ username }}/lightbulb/{{ item }}
  with_items:
    - aws_lab_setup
    - resources
    - Vagrantfile
    - README.md

- name: Install AWS ansible.cfg in home directory
  copy:
    src: ansible.cfg
    dest: /home/{{ username }}/.ansible.cfg
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create lab inventory directory
  file:
    state: directory
    path: /home/{{ username }}/lightbulb/lessons/lab_inventory

- name: Setup student inventory in proper spot
  copy:
    src: ./{{ username }}-instances.txt
    dest: /home/{{ username }}/lightbulb/lessons/lab_inventory/hosts
  when: "username in inventory_hostname"

- name: Update Perms from home dir down
  file:
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    path: /home/{{ username }}
